#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef QLIROONE_SWIFT_H
#define QLIROONE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="QliroOne",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// A customer’s address, as reported by the checkout through
/// <code>QliroOneListener.onCustomerInfoChanged(customer:)</code>.
/// Every field is optional because the checkout fills them in as the customer identifies
/// themselves — expect <code>nil</code> early in a session. Until the customer has been identified the values
/// are masked, which <code>isMasked</code> reports.
SWIFT_CLASS("_TtC8QliroOne7Address")
@interface Address : NSObject
/// The customer’s first name.
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
/// The customer’s last name.
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
/// Street address, including street number.
@property (nonatomic, readonly, copy) NSString * _Nullable street;
/// Care-of line, when the delivery is addressed via someone else.
@property (nonatomic, readonly, copy) NSString * _Nullable careOf;
/// City or town.
@property (nonatomic, readonly, copy) NSString * _Nullable city;
/// Postal code.
@property (nonatomic, readonly, copy) NSString * _Nullable postalCode;
/// <code>true</code> while the checkout is masking the address because the customer has not identified
/// themselves yet. Masked values are partial and must not be treated as a real address.
@property (nonatomic, readonly) BOOL isMasked;
@end

/// The checkout lifecycle, as reported by <code>QliroOneCheckout.checkoutState</code> and
/// <code>QliroOneListener.onStateChanged(state:previousState:)</code>.
/// The happy path runs <code>idle → loading → ready → paymentInProgress → ready → completed</code>. <code>error</code> is
/// recoverable rather than terminal: reloading the order returns the checkout to <code>loading</code>.
/// The states and their <code>value</code> strings are identical on Android and React Native.
typedef SWIFT_ENUM(NSInteger, CheckoutState, open) {
/// No checkout loaded yet.
  CheckoutStateIdle = 0,
/// <code>loadOrderHtml(html:)</code> was called and the checkout is loading.
  CheckoutStateLoading = 1,
/// The checkout finished loading and the customer can interact with it.
  CheckoutStateReady = 2,
/// A payment or authorization is under way and the checkout is locked.
  CheckoutStatePaymentInProgress = 3,
/// The purchase completed and the customer should be sent to the confirmation.
  CheckoutStateCompleted = 4,
/// A fatal error occurred; the matching <code>onError</code> reports which. Recover by reloading the order.
  CheckoutStateError = 5,
};

/// The customer identified in the checkout, reported through
/// <code>QliroOneListener.onCustomerInfoChanged(customer:)</code>.
/// Fields fill in as the customer completes the checkout, and are masked until they have identified
/// themselves (see <code>Address.isMasked</code>). This is personal data: keep only what the integration
/// genuinely needs, and treat <code>personalNumber</code> as sensitive.
SWIFT_CLASS("_TtC8QliroOne8Customer")
@interface Customer : NSObject
/// The customer’s email address.
@property (nonatomic, readonly, copy) NSString * _Nullable email;
/// The customer’s mobile number.
@property (nonatomic, readonly, copy) NSString * _Nullable mobileNumber;
/// The billing address.
@property (nonatomic, readonly, strong) Address * _Nullable address;
/// National identity number, for a private customer.
@property (nonatomic, readonly, copy) NSString * _Nullable personalNumber;
/// Organization number, when the purchase is a business (B2B) one.
@property (nonatomic, readonly, copy) NSString * _Nullable organizationNumber;
@end

/// An optional module on the result (“thank you”) page, for use with
/// <code>QliroOneActions.excludeResultModules(modules:)</code> when the host application renders its own
/// confirmation instead.
typedef SWIFT_ENUM(NSInteger, Module, open) {
/// Header saying “Thank you for your purchase”.
  ModuleHEADER = 0,
/// Total price and order summary.
  ModuleTOTAL_PRICE = 1,
/// Customer contact details and address used in the purchase.
  ModuleCUSTOMER_DETAILS = 2,
/// The selected shipping method. Will only be shown if Qliro One handled the shipping.
  ModuleSHIPPING_METHOD = 3,
};

@class OrderItem;
/// The order as Qliro One currently holds it, delivered to
/// <code>QliroOneListener.onOrderUpdated(order:)</code> during an order sync.
/// Compare it against the host application’s own cart; once they agree, call
/// <code>removeOrderUpdateCallback()</code> and <code>unlock()</code>.
SWIFT_CLASS("_TtC8QliroOne5Order")
@interface Order : NSObject
/// The version Qliro One assigns to each merchant-driven order update. Use it to tell a fresh
/// update apart from a repeat of one already handled.
@property (nonatomic, readonly, copy) NSString * _Nullable merchantUpdateVersion;
/// The order total, including VAT.
@property (nonatomic, readonly) double totalPrice;
/// The order lines.
@property (nonatomic, readonly, copy) NSArray<OrderItem *> * _Nonnull orderItems;
@end

/// A single line of an <code>Order</code>.
SWIFT_CLASS("_TtC8QliroOne9OrderItem")
@interface OrderItem : NSObject
/// The merchant’s own identifier for the product — the reference supplied when the order was
/// created, and the key to match a line back to the host application’s cart.
@property (nonatomic, readonly, copy) NSString * _Nonnull merchantReference;
/// Unit price, including VAT.
@property (nonatomic, readonly) double pricePerItemIncVat;
/// Number of units on this line.
@property (nonatomic, readonly) NSInteger quantity;
@end

/// The payment method the customer has selected, reported through
/// <code>QliroOneListener.onPaymentMethodChanged(paymentMethod:)</code>. Use it to apply payment-method-based
/// discounts or fees.
SWIFT_CLASS("_TtC8QliroOne13PaymentMethod")
@interface PaymentMethod : NSObject
/// The method the customer picked — for example invoice, card, Swish or Trustly.
@property (nonatomic, readonly, copy) NSString * _Nullable method;
/// The variant of <code>method</code>, where one exists (such as a specific invoice or campaign option).
@property (nonatomic, readonly, copy) NSString * _Nullable subtype;
/// Any fee the method itself adds, including VAT. <code>0</code> when the method is free.
@property (nonatomic, readonly) double price;
/// The same fee excluding VAT.
@property (nonatomic, readonly) double priceExVat;
@end

/// Delivered with <code>QliroOneListener.onCompletePurchaseRedirect(options:)</code> when a purchase
/// completes, carrying what the host application needs to show its own confirmation.
SWIFT_CLASS("_TtC8QliroOne23PurchaseRedirectOptions")
@interface PurchaseRedirectOptions : NSObject
/// The merchant confirmation URL — the <code>successUrl</code> supplied when the order was created.
/// Present it, or navigate to the equivalent screen in the app.
@property (nonatomic, readonly, copy) NSString * _Nonnull merchantConfirmationUrl;
@end

@protocol QliroOneListener;
@class NSCoder;
/// The Qliro One checkout view.
/// <h2>Threading contract</h2>
/// The contract below used to be prose, enforced by hand with <code>qliroOnMain</code>. It is now a property of
/// the types: this class is <code>@MainActor</code>, as are <code>QliroOneListener</code>, <code>QliroOneCallbacks</code> and
/// <code>QliroOneActions</code>. The compiler checks what the comment used to assert.
/// <ul>
///   <li>
///     <em>Every <code>QliroOneListener</code> callback is delivered on the main thread.</em> Integrators can update
///     UIKit views directly from a callback.
///   </li>
///   <li>
///     <em>Every method on this class is main-actor isolated</em>, which is what a <code>UIView</code> subclass has
///     always been in fact. The one deliberate exception is <code>loadOrderHtml(html:)</code>, which stays
///     <code>nonisolated</code> and marshals internally: the SDK has always documented it as callable from any
///     thread, and the React Native bridge calls it from one.
///   </li>
///   <li>
///     <code>checkoutState</code> is written only on the main thread; read it from there.
///   </li>
/// </ul>
/// <h2>Where the rest of it lives</h2>
/// This file holds the view itself — its state, its subview, and the public entry points. The
/// behaviour is split by concern across <code>QliroOneCheckout+…</code> files: <code>ApplePay</code> presents and
/// authorizes the payment sheet, <code>Actions</code> is the <code>q1</code> command surface, <code>WebViewEvents</code> relays what
/// the web layer raises, and <code>Observability</code> owns state transitions, telemetry and error reporting.
SWIFT_CLASS("_TtC8QliroOne16QliroOneCheckout")
@interface QliroOneCheckout : UIView
/// The listener receiving checkout events. Every callback on it is delivered on the main thread.
/// <em>Held weakly</em>, like a UIKit delegate: the usual arrangement, where a view controller owns the
/// checkout and is also its listener, does not leak. Something else must own the listener — a
/// listener assigned as <code>checkout.qliroOneListener = MyListener()</code> is deallocated immediately and
/// no callbacks arrive.
@property (nonatomic, weak) id <QliroOneListener> _Nullable qliroOneListener;
/// The Apple Pay merchant identifier (<code>merchant.…</code>) the SDK uses when it builds the
/// <code>PKPaymentRequest</code> and presents the payment sheet.
/// Required for Apple Pay: set it before loading the order. It must be registered in the Apple
/// Developer portal, listed in the host app’s <code>com.apple.developer.in-app-payments</code> entitlement,
/// and enabled for the Qliro account. Leave it <code>nil</code> to run without Apple Pay — the other payment
/// methods are unaffected.
@property (nonatomic, copy) NSString * _Nullable applePayMerchantId;
/// Whether new checkouts are built with WebKit’s app-bound-domain restriction turned on.
/// <em>Off by default, and it must stay off by default.</em> Turning it on is a decision only the host
/// application can make, because it only works if the host application has already done something.
/// <code>WKWebViewConfiguration.limitsNavigationsToAppBoundDomains</code> is the WebKit-enforced form of the
/// navigation allowlist in <code>QliroOneWebView+Navigation.swift</code> — the same rule, applied by the
/// browser engine instead of by this SDK’s <code>WKNavigationDelegate</code>. Three things stop it from being
/// the default:
/// <ol>
///   <li>
///     <em>It needs a key in the <em>host app’s</em> <code>Info.plist</code>.</em> <code>WKAppBoundDomains</code> (at most ten
///     entries) is what defines “app-bound”, and it cannot be shipped by a framework — an
///     <code>Info.plist</code> inside a pod or an XCFramework is not the app’s. A merchant who upgrades the
///     SDK without adding the key gets a web view that can navigate nowhere. The checkout does not
///     render, there is no error from WebKit that names the cause, and it happens in production
///     rather than at build time.
///   </li>
///   <li>
///     <em>It applies to sub-frames, and the sub-frames are deliberately not Qliro’s.</em> A 3-D Secure
///     challenge is served by the customer’s <em>bank</em> — a host that changes per card, per issuer and
///     per transaction, and that no ten-entry list can enumerate. <code>navigationDecision</code> leaves
///     sub-frames un-gated for exactly this reason (see the discussion there). App-bound domains do
///     not offer that exemption, so switching it on unconditionally would fail card payments at the
///     3-D Secure step.
///   </li>
///   <li>
///     <em>The Swift-side allowlist already covers the case that matters.</em> The main frame is held to
///     Qliro’s own domains today, in code this SDK ships and tests. App-bound domains are a
///     belt-and-braces backstop for that rule, not a replacement for it.
///   </li>
/// </ol>
/// So it is offered rather than assumed. Turn it on if — and only if — your app lists Qliro’s
/// checkout domains under <code>WKAppBoundDomains</code>, <em>and</em> your integration does not take card payments
/// that go through 3-D Secure, <em>and</em> you have tested a full purchase end to end with it on.
/// \code
/// <key>WKAppBoundDomains</key>
/// <array>
///     <string>qliro.com</string>
/// </array>
///
/// \endcodeA static rather than an instance property because <code>WKWebViewConfiguration</code> is copied when the
/// <code>WKWebView</code> is created: the choice has to be made before a checkout is constructed, not on one
/// that already exists. Set it once at launch. Checkouts created before it is set are unaffected.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL limitsNavigationsToAppBoundDomains;)
+ (BOOL)limitsNavigationsToAppBoundDomains SWIFT_WARN_UNUSED_RESULT;
+ (void)setLimitsNavigationsToAppBoundDomains:(BOOL)value;
/// URL schemes the checkout may hand to another app, on top of the ones the SDK knows.
/// The SDK opens a fixed set — <code>tel</code>, <code>sms</code>, <code>mailto</code>, <code>https</code>, and the BankID/Swish/Vipps/MobilePay
/// payment apps (see <code>QliroOneTrustedOrigins.allowedExternalSchemes</code>) — and refuses the rest with
/// <code>QliroOneErrorCode.untrustedOrigin</code>, so a frame on the checkout page cannot use the SDK to
/// launch arbitrary installed apps.
/// Add your own return scheme here if a payment flow in your integration comes back to your app
/// through one. Matched case-insensitively, and the scheme only — <code>["myshop"]</code>, not
/// <code>["myshop://return"]</code>.
/// A registered scheme is honoured however the checkout reaches it: a <code>target="_blank"</code> popup, and
/// a navigation of the checkout’s own main frame — which is what a redirect back from a payment
/// app, or a “Return to shop” link, actually produces. In both cases the URL is handed to your app
/// and the navigation is cancelled; the checkout’s web view never loads it.
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull additionalAllowedUrlSchemes;
/// The current checkout lifecycle state. Observe changes via <code>QliroOneListener.onStateChanged</code>.
/// Read-only to integrators. <code>internal(set)</code> rather than <code>private(set)</code> because the only writer,
/// <code>transitionState</code>, lives in QliroOneCheckout+Observability.swift.
@property (nonatomic, readonly) enum CheckoutState checkoutState;
/// Milliseconds to wait for the checkout to load before reporting <code>checkout_load_timeout</code>.
/// Set to 0 to disable. Mirrors the Android SDK (default 30s).
@property (nonatomic) NSInteger loadTimeoutMs;
/// When true, the SDK emits verbose <code>onLog(level: "debug", …)</code> messages. Default false.
@property (nonatomic) BOOL isDebugEnabled;
/// Whether the checkout scrolls its own content.
/// Set it to <code>false</code> when embedding the checkout in a host scroll view: the checkout then sizes
/// itself to its content and reports height changes through
/// <code>QliroOneListener.onCheckoutHeightChanged(height:)</code>, and the host must forward its scroll
/// position with <code>onScroll(containerHeight:offset:)</code> so popups stay correctly positioned.
@property (nonatomic) BOOL isScrollEnabled;
/// Creates a checkout that reports a React Native wrapper version alongside its own in telemetry.
/// For the React Native bridge. Native integrations should use <code>init(frame:)</code>.
/// \param reactNativeSDKVersion The version of the React Native SDK wrapping this checkout.
///
- (nonnull instancetype)initWithReactNativeSDKVersion:(NSString * _Nullable)reactNativeSDKVersion OBJC_DESIGNATED_INITIALIZER;
/// Creates a checkout view. Set <code>qliroOneListener</code>, then call <code>loadOrderHtml(html:)</code>.
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

@interface QliroOneCheckout (SWIFT_EXTENSION(QliroOne))
/// Loads the order HTML returned by the Qliro <code>createOrder</code> call.
/// Safe to call from any thread — the load, and the callbacks it triggers, are marshalled onto
/// the main thread.
/// <code>nonisolated</code> on purpose, and the only member of this class that is. Everything else is
/// main-actor isolated because a <code>UIView</code> is; this one keeps the documented “call it from any
/// thread” guarantee, which the React Native bridge relies on — it hands the order HTML over from
/// whichever queue the JS thread’s response arrived on.
- (void)loadOrderHtmlWithHtml:(NSString * _Nonnull)html;
/// Dismisses the in-app Safari view controller the checkout opened for an external hand-off (a
/// BankID or bank redirect, say) and drops the child web view behind it.
/// The SDK dismisses it on its own when the flow finishes; call this when the host application
/// needs to tear the flow down early — for example because the customer navigated away.
- (void)dismissSafariViewController;
@end

@interface QliroOneCheckout (SWIFT_EXTENSION(QliroOne))
/// Tells the checkout where it currently sits in the host’s scroll view, so popups can be
/// positioned against the visible viewport.
/// Call this from the enclosing scroll view’s <code>scrollViewDidScroll</code> whenever the checkout is
/// embedded content-sized with <code>isScrollEnabled</code> set to <code>false</code>. When the checkout scrolls itself
/// the SDK tracks this internally and calling it is unnecessary.
/// \param containerHeight The height of the scrolling container, in points.
///
/// \param offset The checkout’s offset from the top of that container, in points.
///
- (void)onScrollWithContainerHeight:(NSInteger)containerHeight offset:(NSInteger)offset;
/// Registers interest in session expiry, so <code>QliroOneListener.onSessionExpired()</code> fires instead of
/// Qliro One informing the customer and refreshing the top window itself.
/// Sessions last 90 minutes. Once registered, refreshing is the host application’s
/// responsibility — fetch a new order HTML snippet for the same order and pass it to
/// <code>loadOrderHtml(html:)</code>. See <code>docs/session-refresh.md</code>.
- (void)addSessionExpiredCallback;
/// Stops <code>onSessionExpired()</code> from firing, restoring Qliro One’s default expiry handling.
- (void)removeSessionExpiredCallback;
/// Starts the order sync process: the checkout locks, and
/// <code>QliroOneListener.onOrderUpdated(order:)</code> reports the order as Qliro One holds it.
/// Call it after changing the order from the host application, then compare each update against
/// your own cart and finish with <code>removeOrderUpdateCallback()</code> and <code>unlock()</code>.
- (void)addOrderUpdateCallback;
/// Stops the order sync process. Pair it with <code>unlock()</code> to let the customer continue.
- (void)removeOrderUpdateCallback;
/// Locks the checkout, disabling customer interaction — for instance while the host application
/// updates the order.
- (void)lock;
/// Unlocks the checkout, re-enabling customer interaction.
- (void)unlock;
/// Whether the checkout scrolls itself to the option the customer selects after picking one from
/// an expanded payment or shipping list. Off by default.
/// \param enabled Whether to enable the behaviour.
///
- (void)enableCheckoutScrollingWithEnabled:(BOOL)enabled;
/// Objective-C and React Native entry point to <code>excludeResultModules(modules: [Module])</code>, taking
/// the module names as strings. Names that do not match a <code>Module</code> are ignored.
/// \param modules The module names to exclude, e.g. <code>["HEADER", "TOTAL_PRICE"]</code>.
///
- (void)excludeResultModulesWithModules:(NSArray<NSString *> * _Nonnull)modules;
@end

/// The machine-readable error codes reported through <code>QliroOneListener.onError</code>.
/// <code>value</code> is the wire format: it is the string handed to <code>onError</code>, what the React Native bridge
/// forwards to JS, and what the Android SDK’s <code>QliroOneErrorCode.value</code> produces for the same
/// condition. The strings are stable across releases even if a case is renamed, so integrators
/// should compare against <code>value</code> (or map back with <code>init?(value:)</code>) rather than the case order.
/// The vocabulary is shared with Android; a few codes are only raised by one platform because the
/// underlying condition only exists there (noted per case).
typedef SWIFT_ENUM(NSInteger, QliroOneErrorCode, open) {
/// The main frame of the checkout failed to load (network error, DNS failure, TLS failure).
/// The message carries the underlying <code>NSError</code> description.
  QliroOneErrorCodeLoadFailed = 0,
/// The checkout did not reach <code>CheckoutState.ready</code> within <code>QliroOneCheckout.loadTimeoutMs</code>.
  QliroOneErrorCodeCheckoutLoadTimeout = 1,
/// An external URL or app hand-off could not be opened — a <code>tel:</code>/<code>mailto:</code> link, or a redirect
/// to BankID/Swish/Vipps/MobilePay when that app is not installed. The message names the scheme
/// rather than the full URL, which can carry autostart tokens. Not fatal — the hand-off failed,
/// the checkout is still interactive and the customer can pick another payment method.
  QliroOneErrorCodeOpenUrlFailed = 2,
/// A payload sent by the checkout could not be decoded, so the corresponding
/// <code>QliroOneListener</code> callback was skipped. Android-only today; iOS reports decode failures as
/// an error-level <code>onLog</code> without changing the checkout state.
  QliroOneErrorCodeParseError = 3,
/// The main frame loaded with an HTTP error status. Android-only (<code>WebViewClient</code> surfaces the
/// status; <code>WKNavigationDelegate</code> folds it into the load itself).
  QliroOneErrorCodeHttpError = 4,
/// The WebView render process was terminated by the system, typically out of memory.
/// Android-only — the Android SDK exposes <code>reload()</code> to recover.
  QliroOneErrorCodeWebViewTerminated = 5,
/// The SDK refused something because it did not come from, or was not addressed to, a Qliro
/// origin — a <code>message</code> event from a frame that is not Qliro’s, an Apple Pay <code>proceedUrl</code> or
/// <code>validateMerchantUrl</code> on a host outside <code>QliroOneTrustedOrigins.trustedDomains</code>, a main-frame
/// navigation away from the checkout, or a hand-off to an app scheme the SDK does not know.
/// The message names what was refused; it never carries the offending URL’s path or query, which
/// can hold tokens.
/// Not fatal: the refusal is the SDK declining one operation, and the checkout is still
/// interactive. iOS-only today — the Android SDK does not yet run these checks.
  QliroOneErrorCodeUntrustedOrigin = 6,
};

@class Shipping;
@class NSNumber;
/// Receives the Qliro One checkout events.
/// <em>Threading:</em> the protocol is <code>@MainActor</code>, so every callback is invoked on the main thread and
/// implementations may update UIKit views directly. This used to be a promise in prose enforced by
/// hand inside the SDK; it is now a property of the type, checked by the compiler. Long-running work
/// should still be moved off the main thread by the implementation, as anywhere else in an iOS app.
/// A conforming type declared with this conformance in its primary declaration infers <code>@MainActor</code>
/// for the whole type. That is the intended shape — a listener is UI code — but it is source-breaking
/// for a conformer that was deliberately not main-actor isolated. See MIGRATION.md.
SWIFT_PROTOCOL("_TtP8QliroOne16QliroOneListener_")
@protocol QliroOneListener
/// Called when Qliro One is fully loaded and is ready to get interacted with by the customer.
- (void)onCheckoutLoaded;
/// Called when a customer has updated their information
/// \param customer The updated customer data
///
- (void)onCustomerInfoChangedWithCustomer:(Customer * _Nonnull)customer;
/// This callback activates if a customer clicks the “Not you?” option or chooses to re-authenticate using their personal number during checkout.
/// seealso:
/// <a href="https://developers.qliro.com/docs/qliro-one/frontend-features/listeners#oncustomerdeauthenticating()">Read more</a>
/// <ul>
///   <li>
///   </li>
/// </ul>
- (void)onCustomerDeauthenticating;
/// Called when the user changes payment method or subtype. Use this for applying payment method based discounts.
/// \param paymentMethod The updated payment method
///
- (void)onPaymentMethodChangedWithPaymentMethod:(PaymentMethod * _Nonnull)paymentMethod;
/// Called when a payment has been declined
/// \param declineReason The machine-readable decline reason
///
/// \param declineReasonMessage A human-readable message suitable for display, when the
/// checkout supplied one
///
- (void)onPaymentDeclinedWithDeclineReason:(NSString * _Nonnull)declineReason declineReasonMessage:(NSString * _Nullable)declineReasonMessage;
/// Called when a payment session has started
- (void)onPaymentProcessStart;
/// Called when a payment session has ended
- (void)onPaymentProcessEnd;
/// Called when the checkout session expires — Qliro One sessions are valid for 90 minutes.
/// Only fires once <code>QliroOneActions.addSessionExpiredCallback()</code> has been called; registering it
/// replaces Qliro One’s default behaviour of informing the customer and refreshing the top window.
/// Refresh by fetching a new order HTML snippet for the same order from your backend and passing it
/// to <code>loadOrderHtml(html:)</code>, which restarts the load lifecycle. See <code>docs/session-refresh.md</code>.
/// seealso:
/// <a href="https://developers.qliro.com/docs/qliro-one/frontend-features/listeners#onsessionexpired()">Read more</a>
/// <ul>
///   <li>
///   </li>
/// </ul>
- (void)onSessionExpired;
/// Called when the shipping method has changed
/// \param shipping The updated shipping data
///
- (void)onShippingMethodChangedWithShipping:(Shipping * _Nonnull)shipping;
/// This functionality will be activated if shipping options are provided in the createOrder request and the shipping functionality is used in Qliro One.
/// When the customer changes shipping option so that the shipping fee is affected, the callback will be executed with the new shipping price and new total price for shipping as arguments.
/// The total price includes amounts for the selected additional shipping services. This way the merchant is able to apply amount-based discounts that take the shipping price into account.
/// seealso:
/// <a href="https://developers.qliro.com/docs/qliro-one/frontend-features/listeners#onshippingpricechanged()">Read more</a>
/// <ul>
///   <li>
///   </li>
/// </ul>
/// \param newShippingPrice - The updated price 
///
/// \param newTotalShippingPrice - The updated total price 
///
- (void)onShippingPriceChangedWithNewShippingPrice:(double)newShippingPrice newTotalShippingPrice:(double)newTotalShippingPrice;
/// Called when Qliro One has synced its orders.
/// May fire several times. Once the order matches the host application’s cart, call
/// <code>removeOrderUpdateCallback()</code> and <code>unlock()</code> to let the customer carry on.
/// \param order The order as Qliro One currently holds it
///
- (void)onOrderUpdatedWithOrder:(Order * _Nonnull)order;
/// Called when the checkout requests an Apple Pay authorization, before the SDK presents the sheet.
/// Informational: the SDK builds the <code>PKPaymentRequest</code> and presents Apple Pay itself using
/// <code>applePayMerchantId</code>, so no implementation work is required here. Useful for logging, or for
/// adjusting host UI around the sheet.
/// \param paymentData The payment request data the checkout supplied, when there is any
///
- (void)makePaymentRequestWithPaymentData:(NSDictionary<NSString *, id> * _Nullable)paymentData;
/// Called when Qliro has finished your purchase action
/// <ul>
///   <li>
///   </li>
/// </ul>
/// \param options - An object with data to be used to customize the redirect to your liking. 
///
- (void)onCompletePurchaseRedirectWithOptions:(PurchaseRedirectOptions * _Nonnull)options;
@optional
/// Called when Qliro One changes its height
- (void)onCheckoutHeightChangedWithHeight:(NSInteger)height;
/// Called when the childWebView should be closed
- (void)onClosePopup;
/// Called when an error occurs in the SDK (WebView load failures, network errors, timeouts, etc.).
/// Not every error is fatal: <code>QliroOneErrorCode(value: code)?.isFatal</code> says whether the checkout
/// surface is unusable (<code>checkoutState</code> has moved to <code>.error</code>, so recover with a reload or a fresh
/// order) or whether only one operation failed and the checkout is still interactive.
/// \param code A machine-readable error code. The values are <code>QliroOneErrorCode.value</code> —
/// use <code>QliroOneErrorCode(value: code)</code> to switch on them, or compare the string directly (the
/// strings are the stable wire form, shared with the Android SDK and the React Native bridge).
///
/// \param message A human-readable description.
///
- (void)onErrorWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message;
/// Called when the SDK produces a log message.
/// \param level The log level (“debug”, “info”, “warn”, “error”).
///
/// \param message The log message.
///
- (void)onLogWithLevel:(NSString * _Nonnull)level message:(NSString * _Nonnull)message;
/// Called when the checkout lifecycle state changes. Gives the merchant a transparent view of
/// the order process. State values match across platforms (see CheckoutState).
/// \param state The new state value.
///
/// \param previousState The previous state value.
///
- (void)onStateChangedWithState:(NSString * _Nonnull)state previousState:(NSString * _Nonnull)previousState;
/// Called for lifecycle timing/telemetry events.
/// \param name The event name (e.g. “checkout_loaded”, “payment_process_ended”).
///
/// \param durationMs Duration in milliseconds where applicable, otherwise nil.
///
/// \param metadata Additional event metadata, otherwise nil.
///
- (void)onTelemetryEventWithName:(NSString * _Nonnull)name durationMs:(NSNumber * _Nullable)durationMs metadata:(NSDictionary<NSString *, NSString *> * _Nullable)metadata;
@end

/// The shipping selection, reported through <code>QliroOneListener.onShippingMethodChanged(shipping:)</code>.
/// Only populated when shipping options were supplied in the <code>createOrder</code> request and Qliro One is
/// handling shipping. <code>price</code> covers the method alone; <code>totalShippingPrice</code> adds the selected
/// additional services, and is the figure to use for amount-based discounts.
SWIFT_CLASS("_TtC8QliroOne8Shipping")
@interface Shipping : NSObject
/// The selected shipping method.
@property (nonatomic, readonly, copy) NSString * _Nullable method;
/// A sub-selection within <code>method</code>, where the carrier offers one (such as a pickup location).
@property (nonatomic, readonly, copy) NSString * _Nullable secondaryOption;
/// Additional shipping services the customer has added on top of <code>method</code>.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable additionalShippingServices;
/// The price of the shipping method alone, including VAT.
@property (nonatomic, readonly) double price;
/// The same price excluding VAT.
@property (nonatomic, readonly) double priceExVat;
/// The price of the method plus every selected additional service, including VAT. This is the
/// value <code>QliroOneListener.onShippingPriceChanged</code> reports as <code>newTotalShippingPrice</code>.
@property (nonatomic, readonly) double totalShippingPrice;
/// The same total excluding VAT.
@property (nonatomic, readonly) double totalShippingPriceExVat;
/// Experimental - Might change in the future. If you want to use this feature contact support.
/// *
@property (nonatomic, readonly, copy) NSString * _Nullable accessCode;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.3 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef QLIROONE_SWIFT_H
#define QLIROONE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="QliroOne",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// A customer’s address, as reported by the checkout through
/// <code>QliroOneListener.onCustomerInfoChanged(customer:)</code>.
/// Every field is optional because the checkout fills them in as the customer identifies
/// themselves — expect <code>nil</code> early in a session. Until the customer has been identified the values
/// are masked, which <code>isMasked</code> reports.
SWIFT_CLASS("_TtC8QliroOne7Address")
@interface Address : NSObject
/// The customer’s first name.
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
/// The customer’s last name.
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
/// Street address, including street number.
@property (nonatomic, readonly, copy) NSString * _Nullable street;
/// Care-of line, when the delivery is addressed via someone else.
@property (nonatomic, readonly, copy) NSString * _Nullable careOf;
/// City or town.
@property (nonatomic, readonly, copy) NSString * _Nullable city;
/// Postal code.
@property (nonatomic, readonly, copy) NSString * _Nullable postalCode;
/// <code>true</code> while the checkout is masking the address because the customer has not identified
/// themselves yet. Masked values are partial and must not be treated as a real address.
@property (nonatomic, readonly) BOOL isMasked;
@end

/// The checkout lifecycle, as reported by <code>QliroOneCheckout.checkoutState</code> and
/// <code>QliroOneListener.onStateChanged(state:previousState:)</code>.
/// The happy path runs <code>idle → loading → ready → paymentInProgress → ready → completed</code>. <code>error</code> is
/// recoverable rather than terminal: reloading the order returns the checkout to <code>loading</code>.
/// The states and their <code>value</code> strings are identical on Android and React Native.
typedef SWIFT_ENUM(NSInteger, CheckoutState, open) {
/// No checkout loaded yet.
  CheckoutStateIdle = 0,
/// <code>loadOrderHtml(html:)</code> was called and the checkout is loading.
  CheckoutStateLoading = 1,
/// The checkout finished loading and the customer can interact with it.
  CheckoutStateReady = 2,
/// A payment or authorization is under way and the checkout is locked.
  CheckoutStatePaymentInProgress = 3,
/// The purchase completed and the customer should be sent to the confirmation.
  CheckoutStateCompleted = 4,
/// A fatal error occurred; the matching <code>onError</code> reports which. Recover by reloading the order.
  CheckoutStateError = 5,
};

/// The customer identified in the checkout, reported through
/// <code>QliroOneListener.onCustomerInfoChanged(customer:)</code>.
/// Fields fill in as the customer completes the checkout, and are masked until they have identified
/// themselves (see <code>Address.isMasked</code>). This is personal data: keep only what the integration
/// genuinely needs, and treat <code>personalNumber</code> as sensitive.
SWIFT_CLASS("_TtC8QliroOne8Customer")
@interface Customer : NSObject
/// The customer’s email address.
@property (nonatomic, readonly, copy) NSString * _Nullable email;
/// The customer’s mobile number.
@property (nonatomic, readonly, copy) NSString * _Nullable mobileNumber;
/// The billing address.
@property (nonatomic, readonly, strong) Address * _Nullable address;
/// National identity number, for a private customer.
@property (nonatomic, readonly, copy) NSString * _Nullable personalNumber;
/// Organization number, when the purchase is a business (B2B) one.
@property (nonatomic, readonly, copy) NSString * _Nullable organizationNumber;
@end

/// An optional module on the result (“thank you”) page, for use with
/// <code>QliroOneActions.excludeResultModules(modules:)</code> when the host application renders its own
/// confirmation instead.
typedef SWIFT_ENUM(NSInteger, Module, open) {
/// Header saying “Thank you for your purchase”.
  ModuleHEADER = 0,
/// Total price and order summary.
  ModuleTOTAL_PRICE = 1,
/// Customer contact details and address used in the purchase.
  ModuleCUSTOMER_DETAILS = 2,
/// The selected shipping method. Will only be shown if Qliro One handled the shipping.
  ModuleSHIPPING_METHOD = 3,
};

@class OrderItem;
/// The order as Qliro One currently holds it, delivered to
/// <code>QliroOneListener.onOrderUpdated(order:)</code> during an order sync.
/// Compare it against the host application’s own cart; once they agree, call
/// <code>removeOrderUpdateCallback()</code> and <code>unlock()</code>.
SWIFT_CLASS("_TtC8QliroOne5Order")
@interface Order : NSObject
/// The version Qliro One assigns to each merchant-driven order update. Use it to tell a fresh
/// update apart from a repeat of one already handled.
@property (nonatomic, readonly, copy) NSString * _Nullable merchantUpdateVersion;
/// The order total, including VAT.
@property (nonatomic, readonly) double totalPrice;
/// The order lines.
@property (nonatomic, readonly, copy) NSArray<OrderItem *> * _Nonnull orderItems;
@end

/// A single line of an <code>Order</code>.
SWIFT_CLASS("_TtC8QliroOne9OrderItem")
@interface OrderItem : NSObject
/// The merchant’s own identifier for the product — the reference supplied when the order was
/// created, and the key to match a line back to the host application’s cart.
@property (nonatomic, readonly, copy) NSString * _Nonnull merchantReference;
/// Unit price, including VAT.
@property (nonatomic, readonly) double pricePerItemIncVat;
/// Number of units on this line.
@property (nonatomic, readonly) NSInteger quantity;
@end

/// The payment method the customer has selected, reported through
/// <code>QliroOneListener.onPaymentMethodChanged(paymentMethod:)</code>. Use it to apply payment-method-based
/// discounts or fees.
SWIFT_CLASS("_TtC8QliroOne13PaymentMethod")
@interface PaymentMethod : NSObject
/// The method the customer picked — for example invoice, card, Swish or Trustly.
@property (nonatomic, readonly, copy) NSString * _Nullable method;
/// The variant of <code>method</code>, where one exists (such as a specific invoice or campaign option).
@property (nonatomic, readonly, copy) NSString * _Nullable subtype;
/// Any fee the method itself adds, including VAT. <code>0</code> when the method is free.
@property (nonatomic, readonly) double price;
/// The same fee excluding VAT.
@property (nonatomic, readonly) double priceExVat;
@end

/// Delivered with <code>QliroOneListener.onCompletePurchaseRedirect(options:)</code> when a purchase
/// completes, carrying what the host application needs to show its own confirmation.
SWIFT_CLASS("_TtC8QliroOne23PurchaseRedirectOptions")
@interface PurchaseRedirectOptions : NSObject
/// The merchant confirmation URL — the <code>successUrl</code> supplied when the order was created.
/// Present it, or navigate to the equivalent screen in the app.
@property (nonatomic, readonly, copy) NSString * _Nonnull merchantConfirmationUrl;
@end

@protocol QliroOneListener;
@class NSCoder;
/// The Qliro One checkout view.
/// <h2>Threading contract</h2>
/// The contract below used to be prose, enforced by hand with <code>qliroOnMain</code>. It is now a property of
/// the types: this class is <code>@MainActor</code>, as are <code>QliroOneListener</code>, <code>QliroOneCallbacks</code> and
/// <code>QliroOneActions</code>. The compiler checks what the comment used to assert.
/// <ul>
///   <li>
///     <em>Every <code>QliroOneListener</code> callback is delivered on the main thread.</em> Integrators can update
///     UIKit views directly from a callback.
///   </li>
///   <li>
///     <em>Every method on this class is main-actor isolated</em>, which is what a <code>UIView</code> subclass has
///     always been in fact. The one deliberate exception is <code>loadOrderHtml(html:)</code>, which stays
///     <code>nonisolated</code> and marshals internally: the SDK has always documented it as callable from any
///     thread, and the React Native bridge calls it from one.
///   </li>
///   <li>
///     <code>checkoutState</code> is written only on the main thread; read it from there.
///   </li>
/// </ul>
/// <h2>Where the rest of it lives</h2>
/// This file holds the view itself — its state, its subview, and the public entry points. The
/// behaviour is split by concern across <code>QliroOneCheckout+…</code> files: <code>ApplePay</code> presents and
/// authorizes the payment sheet, <code>Actions</code> is the <code>q1</code> command surface, <code>WebViewEvents</code> relays what
/// the web layer raises, and <code>Observability</code> owns state transitions, telemetry and error reporting.
SWIFT_CLASS("_TtC8QliroOne16QliroOneCheckout")
@interface QliroOneCheckout : UIView
/// The listener receiving checkout events. Every callback on it is delivered on the main thread.
/// <em>Held weakly</em>, like a UIKit delegate: the usual arrangement, where a view controller owns the
/// checkout and is also its listener, does not leak. Something else must own the listener — a
/// listener assigned as <code>checkout.qliroOneListener = MyListener()</code> is deallocated immediately and
/// no callbacks arrive.
@property (nonatomic, weak) id <QliroOneListener> _Nullable qliroOneListener;
/// The Apple Pay merchant identifier (<code>merchant.…</code>) the SDK uses when it builds the
/// <code>PKPaymentRequest</code> and presents the payment sheet.
/// Required for Apple Pay: set it before loading the order. It must be registered in the Apple
/// Developer portal, listed in the host app’s <code>com.apple.developer.in-app-payments</code> entitlement,
/// and enabled for the Qliro account. Leave it <code>nil</code> to run without Apple Pay — the other payment
/// methods are unaffected.
@property (nonatomic, copy) NSString * _Nullable applePayMerchantId;
/// Whether new checkouts are built with WebKit’s app-bound-domain restriction turned on.
/// <em>Off by default, and it must stay off by default.</em> Turning it on is a decision only the host
/// application can make, because it only works if the host application has already done something.
/// <code>WKWebViewConfiguration.limitsNavigationsToAppBoundDomains</code> is the WebKit-enforced form of the
/// navigation allowlist in <code>QliroOneWebView+Navigation.swift</code> — the same rule, applied by the
/// browser engine instead of by this SDK’s <code>WKNavigationDelegate</code>. Three things stop it from being
/// the default:
/// <ol>
///   <li>
///     <em>It needs a key in the <em>host app’s</em> <code>Info.plist</code>.</em> <code>WKAppBoundDomains</code> (at most ten
///     entries) is what defines “app-bound”, and it cannot be shipped by a framework — an
///     <code>Info.plist</code> inside a pod or an XCFramework is not the app’s. A merchant who upgrades the
///     SDK without adding the key gets a web view that can navigate nowhere. The checkout does not
///     render, there is no error from WebKit that names the cause, and it happens in production
///     rather than at build time.
///   </li>
///   <li>
///     <em>It applies to sub-frames, and the sub-frames are deliberately not Qliro’s.</em> A 3-D Secure
///     challenge is served by the customer’s <em>bank</em> — a host that changes per card, per issuer and
///     per transaction, and that no ten-entry list can enumerate. <code>navigationDecision</code> leaves
///     sub-frames un-gated for exactly this reason (see the discussion there). App-bound domains do
///     not offer that exemption, so switching it on unconditionally would fail card payments at the
///     3-D Secure step.
///   </li>
///   <li>
///     <em>The Swift-side allowlist already covers the case that matters.</em> The main frame is held to
///     Qliro’s own domains today, in code this SDK ships and tests. App-bound domains are a
///     belt-and-braces backstop for that rule, not a replacement for it.
///   </li>
/// </ol>
/// So it is offered rather than assumed. Turn it on if — and only if — your app lists Qliro’s
/// checkout domains under <code>WKAppBoundDomains</code>, <em>and</em> your integration does not take card payments
/// that go through 3-D Secure, <em>and</em> you have tested a full purchase end to end with it on.
/// \code
/// <key>WKAppBoundDomains</key>
/// <array>
///     <string>qliro.com</string>
/// </array>
///
/// \endcodeA static rather than an instance property because <code>WKWebViewConfiguration</code> is copied when the
/// <code>WKWebView</code> is created: the choice has to be made before a checkout is constructed, not on one
/// that already exists. Set it once at launch. Checkouts created before it is set are unaffected.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL limitsNavigationsToAppBoundDomains;)
+ (BOOL)limitsNavigationsToAppBoundDomains SWIFT_WARN_UNUSED_RESULT;
+ (void)setLimitsNavigationsToAppBoundDomains:(BOOL)value;
/// URL schemes the checkout may hand to another app, on top of the ones the SDK knows.
/// The SDK opens a fixed set — <code>tel</code>, <code>sms</code>, <code>mailto</code>, <code>https</code>, and the BankID/Swish/Vipps/MobilePay
/// payment apps (see <code>QliroOneTrustedOrigins.allowedExternalSchemes</code>) — and refuses the rest with
/// <code>QliroOneErrorCode.untrustedOrigin</code>, so a frame on the checkout page cannot use the SDK to
/// launch arbitrary installed apps.
/// Add your own return scheme here if a payment flow in your integration comes back to your app
/// through one. Matched case-insensitively, and the scheme only — <code>["myshop"]</code>, not
/// <code>["myshop://return"]</code>.
/// A registered scheme is honoured however the checkout reaches it: a <code>target="_blank"</code> popup, and
/// a navigation of the checkout’s own main frame — which is what a redirect back from a payment
/// app, or a “Return to shop” link, actually produces. In both cases the URL is handed to your app
/// and the navigation is cancelled; the checkout’s web view never loads it.
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull additionalAllowedUrlSchemes;
/// The current checkout lifecycle state. Observe changes via <code>QliroOneListener.onStateChanged</code>.
/// Read-only to integrators. <code>internal(set)</code> rather than <code>private(set)</code> because the only writer,
/// <code>transitionState</code>, lives in QliroOneCheckout+Observability.swift.
@property (nonatomic, readonly) enum CheckoutState checkoutState;
/// Milliseconds to wait for the checkout to load before reporting <code>checkout_load_timeout</code>.
/// Set to 0 to disable. Mirrors the Android SDK (default 30s).
@property (nonatomic) NSInteger loadTimeoutMs;
/// When true, the SDK emits verbose <code>onLog(level: "debug", …)</code> messages. Default false.
@property (nonatomic) BOOL isDebugEnabled;
/// Whether the checkout scrolls its own content.
/// Set it to <code>false</code> when embedding the checkout in a host scroll view: the checkout then sizes
/// itself to its content and reports height changes through
/// <code>QliroOneListener.onCheckoutHeightChanged(height:)</code>, and the host must forward its scroll
/// position with <code>onScroll(containerHeight:offset:)</code> so popups stay correctly positioned.
@property (nonatomic) BOOL isScrollEnabled;
/// Creates a checkout that reports a React Native wrapper version alongside its own in telemetry.
/// For the React Native bridge. Native integrations should use <code>init(frame:)</code>.
/// \param reactNativeSDKVersion The version of the React Native SDK wrapping this checkout.
///
- (nonnull instancetype)initWithReactNativeSDKVersion:(NSString * _Nullable)reactNativeSDKVersion OBJC_DESIGNATED_INITIALIZER;
/// Creates a checkout view. Set <code>qliroOneListener</code>, then call <code>loadOrderHtml(html:)</code>.
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

@interface QliroOneCheckout (SWIFT_EXTENSION(QliroOne))
/// Loads the order HTML returned by the Qliro <code>createOrder</code> call.
/// Safe to call from any thread — the load, and the callbacks it triggers, are marshalled onto
/// the main thread.
/// <code>nonisolated</code> on purpose, and the only member of this class that is. Everything else is
/// main-actor isolated because a <code>UIView</code> is; this one keeps the documented “call it from any
/// thread” guarantee, which the React Native bridge relies on — it hands the order HTML over from
/// whichever queue the JS thread’s response arrived on.
- (void)loadOrderHtmlWithHtml:(NSString * _Nonnull)html;
/// Dismisses the in-app Safari view controller the checkout opened for an external hand-off (a
/// BankID or bank redirect, say) and drops the child web view behind it.
/// The SDK dismisses it on its own when the flow finishes; call this when the host application
/// needs to tear the flow down early — for example because the customer navigated away.
- (void)dismissSafariViewController;
@end

@interface QliroOneCheckout (SWIFT_EXTENSION(QliroOne))
/// Tells the checkout where it currently sits in the host’s scroll view, so popups can be
/// positioned against the visible viewport.
/// Call this from the enclosing scroll view’s <code>scrollViewDidScroll</code> whenever the checkout is
/// embedded content-sized with <code>isScrollEnabled</code> set to <code>false</code>. When the checkout scrolls itself
/// the SDK tracks this internally and calling it is unnecessary.
/// \param containerHeight The height of the scrolling container, in points.
///
/// \param offset The checkout’s offset from the top of that container, in points.
///
- (void)onScrollWithContainerHeight:(NSInteger)containerHeight offset:(NSInteger)offset;
/// Registers interest in session expiry, so <code>QliroOneListener.onSessionExpired()</code> fires instead of
/// Qliro One informing the customer and refreshing the top window itself.
/// Sessions last 90 minutes. Once registered, refreshing is the host application’s
/// responsibility — fetch a new order HTML snippet for the same order and pass it to
/// <code>loadOrderHtml(html:)</code>. See <code>docs/session-refresh.md</code>.
- (void)addSessionExpiredCallback;
/// Stops <code>onSessionExpired()</code> from firing, restoring Qliro One’s default expiry handling.
- (void)removeSessionExpiredCallback;
/// Starts the order sync process: the checkout locks, and
/// <code>QliroOneListener.onOrderUpdated(order:)</code> reports the order as Qliro One holds it.
/// Call it after changing the order from the host application, then compare each update against
/// your own cart and finish with <code>removeOrderUpdateCallback()</code> and <code>unlock()</code>.
- (void)addOrderUpdateCallback;
/// Stops the order sync process. Pair it with <code>unlock()</code> to let the customer continue.
- (void)removeOrderUpdateCallback;
/// Locks the checkout, disabling customer interaction — for instance while the host application
/// updates the order.
- (void)lock;
/// Unlocks the checkout, re-enabling customer interaction.
- (void)unlock;
/// Whether the checkout scrolls itself to the option the customer selects after picking one from
/// an expanded payment or shipping list. Off by default.
/// \param enabled Whether to enable the behaviour.
///
- (void)enableCheckoutScrollingWithEnabled:(BOOL)enabled;
/// Objective-C and React Native entry point to <code>excludeResultModules(modules: [Module])</code>, taking
/// the module names as strings. Names that do not match a <code>Module</code> are ignored.
/// \param modules The module names to exclude, e.g. <code>["HEADER", "TOTAL_PRICE"]</code>.
///
- (void)excludeResultModulesWithModules:(NSArray<NSString *> * _Nonnull)modules;
@end

/// The machine-readable error codes reported through <code>QliroOneListener.onError</code>.
/// <code>value</code> is the wire format: it is the string handed to <code>onError</code>, what the React Native bridge
/// forwards to JS, and what the Android SDK’s <code>QliroOneErrorCode.value</code> produces for the same
/// condition. The strings are stable across releases even if a case is renamed, so integrators
/// should compare against <code>value</code> (or map back with <code>init?(value:)</code>) rather than the case order.
/// The vocabulary is shared with Android; a few codes are only raised by one platform because the
/// underlying condition only exists there (noted per case).
typedef SWIFT_ENUM(NSInteger, QliroOneErrorCode, open) {
/// The main frame of the checkout failed to load (network error, DNS failure, TLS failure).
/// The message carries the underlying <code>NSError</code> description.
  QliroOneErrorCodeLoadFailed = 0,
/// The checkout did not reach <code>CheckoutState.ready</code> within <code>QliroOneCheckout.loadTimeoutMs</code>.
  QliroOneErrorCodeCheckoutLoadTimeout = 1,
/// An external URL or app hand-off could not be opened — a <code>tel:</code>/<code>mailto:</code> link, or a redirect
/// to BankID/Swish/Vipps/MobilePay when that app is not installed. The message names the scheme
/// rather than the full URL, which can carry autostart tokens. Not fatal — the hand-off failed,
/// the checkout is still interactive and the customer can pick another payment method.
  QliroOneErrorCodeOpenUrlFailed = 2,
/// A payload sent by the checkout could not be decoded, so the corresponding
/// <code>QliroOneListener</code> callback was skipped. Android-only today; iOS reports decode failures as
/// an error-level <code>onLog</code> without changing the checkout state.
  QliroOneErrorCodeParseError = 3,
/// The main frame loaded with an HTTP error status. Android-only (<code>WebViewClient</code> surfaces the
/// status; <code>WKNavigationDelegate</code> folds it into the load itself).
  QliroOneErrorCodeHttpError = 4,
/// The WebView render process was terminated by the system, typically out of memory.
/// Android-only — the Android SDK exposes <code>reload()</code> to recover.
  QliroOneErrorCodeWebViewTerminated = 5,
/// The SDK refused something because it did not come from, or was not addressed to, a Qliro
/// origin — a <code>message</code> event from a frame that is not Qliro’s, an Apple Pay <code>proceedUrl</code> or
/// <code>validateMerchantUrl</code> on a host outside <code>QliroOneTrustedOrigins.trustedDomains</code>, a main-frame
/// navigation away from the checkout, or a hand-off to an app scheme the SDK does not know.
/// The message names what was refused; it never carries the offending URL’s path or query, which
/// can hold tokens.
/// Not fatal: the refusal is the SDK declining one operation, and the checkout is still
/// interactive. iOS-only today — the Android SDK does not yet run these checks.
  QliroOneErrorCodeUntrustedOrigin = 6,
};

@class Shipping;
@class NSNumber;
/// Receives the Qliro One checkout events.
/// <em>Threading:</em> the protocol is <code>@MainActor</code>, so every callback is invoked on the main thread and
/// implementations may update UIKit views directly. This used to be a promise in prose enforced by
/// hand inside the SDK; it is now a property of the type, checked by the compiler. Long-running work
/// should still be moved off the main thread by the implementation, as anywhere else in an iOS app.
/// A conforming type declared with this conformance in its primary declaration infers <code>@MainActor</code>
/// for the whole type. That is the intended shape — a listener is UI code — but it is source-breaking
/// for a conformer that was deliberately not main-actor isolated. See MIGRATION.md.
SWIFT_PROTOCOL("_TtP8QliroOne16QliroOneListener_")
@protocol QliroOneListener
/// Called when Qliro One is fully loaded and is ready to get interacted with by the customer.
- (void)onCheckoutLoaded;
/// Called when a customer has updated their information
/// \param customer The updated customer data
///
- (void)onCustomerInfoChangedWithCustomer:(Customer * _Nonnull)customer;
/// This callback activates if a customer clicks the “Not you?” option or chooses to re-authenticate using their personal number during checkout.
/// seealso:
/// <a href="https://developers.qliro.com/docs/qliro-one/frontend-features/listeners#oncustomerdeauthenticating()">Read more</a>
/// <ul>
///   <li>
///   </li>
/// </ul>
- (void)onCustomerDeauthenticating;
/// Called when the user changes payment method or subtype. Use this for applying payment method based discounts.
/// \param paymentMethod The updated payment method
///
- (void)onPaymentMethodChangedWithPaymentMethod:(PaymentMethod * _Nonnull)paymentMethod;
/// Called when a payment has been declined
/// \param declineReason The machine-readable decline reason
///
/// \param declineReasonMessage A human-readable message suitable for display, when the
/// checkout supplied one
///
- (void)onPaymentDeclinedWithDeclineReason:(NSString * _Nonnull)declineReason declineReasonMessage:(NSString * _Nullable)declineReasonMessage;
/// Called when a payment session has started
- (void)onPaymentProcessStart;
/// Called when a payment session has ended
- (void)onPaymentProcessEnd;
/// Called when the checkout session expires — Qliro One sessions are valid for 90 minutes.
/// Only fires once <code>QliroOneActions.addSessionExpiredCallback()</code> has been called; registering it
/// replaces Qliro One’s default behaviour of informing the customer and refreshing the top window.
/// Refresh by fetching a new order HTML snippet for the same order from your backend and passing it
/// to <code>loadOrderHtml(html:)</code>, which restarts the load lifecycle. See <code>docs/session-refresh.md</code>.
/// seealso:
/// <a href="https://developers.qliro.com/docs/qliro-one/frontend-features/listeners#onsessionexpired()">Read more</a>
/// <ul>
///   <li>
///   </li>
/// </ul>
- (void)onSessionExpired;
/// Called when the shipping method has changed
/// \param shipping The updated shipping data
///
- (void)onShippingMethodChangedWithShipping:(Shipping * _Nonnull)shipping;
/// This functionality will be activated if shipping options are provided in the createOrder request and the shipping functionality is used in Qliro One.
/// When the customer changes shipping option so that the shipping fee is affected, the callback will be executed with the new shipping price and new total price for shipping as arguments.
/// The total price includes amounts for the selected additional shipping services. This way the merchant is able to apply amount-based discounts that take the shipping price into account.
/// seealso:
/// <a href="https://developers.qliro.com/docs/qliro-one/frontend-features/listeners#onshippingpricechanged()">Read more</a>
/// <ul>
///   <li>
///   </li>
/// </ul>
/// \param newShippingPrice - The updated price 
///
/// \param newTotalShippingPrice - The updated total price 
///
- (void)onShippingPriceChangedWithNewShippingPrice:(double)newShippingPrice newTotalShippingPrice:(double)newTotalShippingPrice;
/// Called when Qliro One has synced its orders.
/// May fire several times. Once the order matches the host application’s cart, call
/// <code>removeOrderUpdateCallback()</code> and <code>unlock()</code> to let the customer carry on.
/// \param order The order as Qliro One currently holds it
///
- (void)onOrderUpdatedWithOrder:(Order * _Nonnull)order;
/// Called when the checkout requests an Apple Pay authorization, before the SDK presents the sheet.
/// Informational: the SDK builds the <code>PKPaymentRequest</code> and presents Apple Pay itself using
/// <code>applePayMerchantId</code>, so no implementation work is required here. Useful for logging, or for
/// adjusting host UI around the sheet.
/// \param paymentData The payment request data the checkout supplied, when there is any
///
- (void)makePaymentRequestWithPaymentData:(NSDictionary<NSString *, id> * _Nullable)paymentData;
/// Called when Qliro has finished your purchase action
/// <ul>
///   <li>
///   </li>
/// </ul>
/// \param options - An object with data to be used to customize the redirect to your liking. 
///
- (void)onCompletePurchaseRedirectWithOptions:(PurchaseRedirectOptions * _Nonnull)options;
@optional
/// Called when Qliro One changes its height
- (void)onCheckoutHeightChangedWithHeight:(NSInteger)height;
/// Called when the childWebView should be closed
- (void)onClosePopup;
/// Called when an error occurs in the SDK (WebView load failures, network errors, timeouts, etc.).
/// Not every error is fatal: <code>QliroOneErrorCode(value: code)?.isFatal</code> says whether the checkout
/// surface is unusable (<code>checkoutState</code> has moved to <code>.error</code>, so recover with a reload or a fresh
/// order) or whether only one operation failed and the checkout is still interactive.
/// \param code A machine-readable error code. The values are <code>QliroOneErrorCode.value</code> —
/// use <code>QliroOneErrorCode(value: code)</code> to switch on them, or compare the string directly (the
/// strings are the stable wire form, shared with the Android SDK and the React Native bridge).
///
/// \param message A human-readable description.
///
- (void)onErrorWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message;
/// Called when the SDK produces a log message.
/// \param level The log level (“debug”, “info”, “warn”, “error”).
///
/// \param message The log message.
///
- (void)onLogWithLevel:(NSString * _Nonnull)level message:(NSString * _Nonnull)message;
/// Called when the checkout lifecycle state changes. Gives the merchant a transparent view of
/// the order process. State values match across platforms (see CheckoutState).
/// \param state The new state value.
///
/// \param previousState The previous state value.
///
- (void)onStateChangedWithState:(NSString * _Nonnull)state previousState:(NSString * _Nonnull)previousState;
/// Called for lifecycle timing/telemetry events.
/// \param name The event name (e.g. “checkout_loaded”, “payment_process_ended”).
///
/// \param durationMs Duration in milliseconds where applicable, otherwise nil.
///
/// \param metadata Additional event metadata, otherwise nil.
///
- (void)onTelemetryEventWithName:(NSString * _Nonnull)name durationMs:(NSNumber * _Nullable)durationMs metadata:(NSDictionary<NSString *, NSString *> * _Nullable)metadata;
@end

/// The shipping selection, reported through <code>QliroOneListener.onShippingMethodChanged(shipping:)</code>.
/// Only populated when shipping options were supplied in the <code>createOrder</code> request and Qliro One is
/// handling shipping. <code>price</code> covers the method alone; <code>totalShippingPrice</code> adds the selected
/// additional services, and is the figure to use for amount-based discounts.
SWIFT_CLASS("_TtC8QliroOne8Shipping")
@interface Shipping : NSObject
/// The selected shipping method.
@property (nonatomic, readonly, copy) NSString * _Nullable method;
/// A sub-selection within <code>method</code>, where the carrier offers one (such as a pickup location).
@property (nonatomic, readonly, copy) NSString * _Nullable secondaryOption;
/// Additional shipping services the customer has added on top of <code>method</code>.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable additionalShippingServices;
/// The price of the shipping method alone, including VAT.
@property (nonatomic, readonly) double price;
/// The same price excluding VAT.
@property (nonatomic, readonly) double priceExVat;
/// The price of the method plus every selected additional service, including VAT. This is the
/// value <code>QliroOneListener.onShippingPriceChanged</code> reports as <code>newTotalShippingPrice</code>.
@property (nonatomic, readonly) double totalShippingPrice;
/// The same total excluding VAT.
@property (nonatomic, readonly) double totalShippingPriceExVat;
/// Experimental - Might change in the future. If you want to use this feature contact support.
/// *
@property (nonatomic, readonly, copy) NSString * _Nullable accessCode;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
